# Generated by Django 5.2.7 on 2025-11-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=20)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('mri', models.FileField(upload_to='MRIs/')),
                ('dims', models.JSONField(blank=True, default=list, null=True)),
                ('modality', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('structure_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('structure_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MRI_Masks',
            fields=[
                ('mask_id', models.AutoField(primary_key=True, serialize=False)),
                ('structure_color', models.CharField(max_length=255)),
                ('coordinates', models.JSONField(blank=True, default=list, null=True)),
                ('rater', models.IntegerField(blank=True, null=True)),
                ('mask_path', models.FileField(blank=True, null=True, upload_to='Masks/')),
                ('dims', models.JSONField(blank=True, default=list, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segment.patients')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Segment.structures')),
            ],
        ),
        migrations.CreateModel(
            name='MRI_MASK_Meta_Data',
            fields=[
                ('meta_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Reading', models.CharField(choices=[('Axial', 'A'), ('Coronal', 'C'), ('Saggital', 'S')])),
                ('Rating', models.IntegerField(max_length=4)),
                ('Annotators_num', models.IntegerField()),
                ('mri_mask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segment.mri_masks')),
            ],
        ),
    ]
