# Generated by Django 5.2.7 on 2025-10-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='MRIs/')),
            ],
        ),
        migrations.CreateModel(
            name='MRI_Mask',
            fields=[
                ('mask_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('mask_path', models.ImageField(blank=True, null=True, upload_to='Masks/')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('rater_id', models.IntegerField(blank=True, null=True)),
                ('structure_id', models.IntegerField(blank=True, null=True)),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='Segment.slice')),
            ],
        ),
    ]
