# Generated by Django 5.2.7 on 2026-03-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Segment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patients",
            name="tag",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name="MRI_MASK_Meta_Data",
        ),
    ]
