# Generated by Django 5.2.7 on 2025-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mri_masks',
            name='dims',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
